-- The session protocol's tables: what goes on the wire and what comes off.
local test = require("test")
local wire = require("wire")
local frames = require("frames")

local function define_tests()
    test.describe("wire.frame and wire.delta", function()
        test.it("send only the changed rows, keyed by their zero-based index as a string", function()
            local _, last = frames.delta(nil, {revision = 1, width = 10, height = 4, rows = {"a", "b", "c", "d"}})
            local delta = frames.delta(last, {revision = 2, width = 10, height = 4, rows = {"A", "b", "c", "D"},
                cursor = {x = 3, y = 4, visible = true}})
            local message = wire.frame(7, delta)
            test.eq(message.k, "frame")
            test.eq(message.s, 7)
            test.eq(message.r, 2)
            test.eq(message.w["0"], "A")
            test.eq(message.w["3"], "D")
            test.is_nil(message.w["1"])
            test.is_nil(message.w[1], "no integer keys on the wire")
            test.eq(message.c.x * 10 + message.c.y, 23, "the cursor is zero-based on the wire")
        end)

        test.it("come back as the same one-based delta", function()
            local delta = wire.delta({k = "frame", s = 1, r = 5, x = 10, y = 3, w = {["0"] = "top", ["2"] = "bottom"},
                c = {x = 0, y = 2, visible = false}})
            test.eq(delta.rows[1], "top")
            test.eq(delta.rows[3], "bottom")
            test.is_nil(delta.rows[2])
            test.is_false(delta.full)
            test.eq(delta.changed, 2)
            test.eq(delta.cursor.x * 10 + delta.cursor.y, 13)
            test.eq(delta.revision, 5)
        end)

        test.it("take a frame with every row for a full screen", function()
            local delta = wire.delta({k = "frame", s = 1, r = 1, x = 4, y = 2, w = {["0"] = "a", ["1"] = "b"}})
            test.is_true(delta.full)
        end)

        test.it("drop rows outside the screen and refuse a frame without a size", function()
            local delta = wire.delta({k = "frame", s = 1, r = 1, x = 4, y = 2, w = {["0"] = "a", ["5"] = "far", ["-1"] = "up"}})
            test.eq(delta.changed, 1)
            local none, why = wire.delta({k = "frame", s = 1, w = {}})
            test.is_nil(none)
            test.not_nil(why)
        end)
    end)

    test.describe("wire.safe", function()
        test.it("accepts what survives the hop", function()
            test.is_true(wire.safe({k = "frame", w = {["0"] = "x"}, list = {1, 2, 3}, e = {type = "key"}}))
        end)

        test.it("refuses a table that would lose keys between nodes", function()
            test.is_nil(wire.safe({w = {[0] = "a", [1] = "b"}}), "a key 0")
            test.is_nil(wire.safe({w = {[1] = "a", [3] = "c"}}), "a gap")
            test.is_nil(wire.safe({w = {[1] = "a", k = "b"}}), "list and string keys mixed")
            test.is_nil(wire.safe({deep = {w = {[2] = "b"}}}), "a list not starting at 1, nested")
        end)

        test.it("refuses to send such a message at all", function()
            local sent, why = wire.send("{nobody@nowhere|0x1}", {k = "frame", w = {[1] = "a", [3] = "c"}})
            test.is_nil(sent)
            test.not_nil(string.find(tostring(why), "would not survive the hop", 1, true), tostring(why))
            sent, why = wire.send("{nobody@nowhere|0x1}", {k = "shout"})
            test.is_nil(sent)
            test.not_nil(string.find(tostring(why), "not a session message", 1, true), tostring(why))
        end)
    end)

    test.describe("names and nodes", function()
        test.it("derive the broker's name from the node and read node and host from a PID", function()
            test.eq(wire.broker_name("node-b"), "chicago.rdesktop.broker@node-b")
            test.eq(wire.node_of("{node-b@app:processes|0x00012}"), "node-b")
            test.eq(wire.host_of("{node-b@app:processes|0x00012}"), "app:processes")
            test.is_nil(wire.node_of("not a pid"))
        end)

        test.it("say gone only when a membership list says so", function()
            local members = {{id = "a", is_local = true}, {id = "b"}}
            test.is_true(wire.present(members, "b"))
            test.is_false(wire.present(members, "c"))
            test.is_nil(wire.present(nil, "c"), "no list is not a departure")
        end)
    end)
end

local run_cases = test.run_cases(define_tests)
return {run = function(options) return run_cases(options) end}
